language: node_js
node_js: 10
sudo: required
services:
- docker
cache: yarn
before_install:
- yarn add minimist cross-spawn
script: node scripts/dockerUtil.js build
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  skip_cleanup: true
  script: node scripts/dockerUtil.js publish
  on:
    all_branches: true
env:
  global:
    secure: PcdvxsAA2XEq6KftLwTc3wiu64OptyO9eu1qnCBD4MrhheeinpLkEPbMBJZ8IKu6OrruIa6zierd4tgw9aciDoB9mUZjsvgZChpLREJb9quBXt1XHik/L4XYyW6L6heEVkTIvqEYXCBPsn4FAq/3G9+/fZhDXOfEB/gbXKu9gBJxh6fxaqjAtms8bgPcsmMRUYTVNpK/Mgmt5jGk7p0mmlHrHPxssgqkFccOLY4vYW9HcdsjRkf4IOayMnJTWMltncD1sIrRL9zwOEw3lejKPriO7hFD+yWrNU9ho/ASWmFtjl/+q8rhSNZSyYSstDh7/tH94o1nCuc9ZPpbf1rE5274VktvhhXh+dMGzCVUEfehpTrQIg7HHB09rmwnJEhjQ/dVsWJzvWQ5wmJB5WMXNFcTEQXZsZQcVZNT6H2qRRpVW7yNzQgXfusaewr/1VHovCRFna9coED4USXMIYrij5HiUe/vT4kV5Ec9PmnV9RxAg9euKqj/Rryyt6C+X2tuy5pEmLiW2VGP8OsNcjr2+NEgn39x7mjWfhfe9wgzj3KSYnktlONKqI4+mRs8Vtfl5XI9k9+UAV/V9TxPEHZdx6C8baRDYRvaMVq4ZmTq5uwb93DxtrYb6dKNohlNaW8GXRrVIDddJbMvSSQYeHbv1FBC/s0dv9VrMLq/7TVbcis=
notifications:
  slack:
    secure: QdZPipjbUcPH4/44CMl01bck9Dc4bNOtVGUn9mseE9SPfjJqOV61sD6a+dosJtWFq91+/eeAiP/a4F/nuofvsfb44ar3Ii9UvgclNvj34wSuibGgUK/D6NH9CxE+sRNrYJ97/vE9JIz0GUQtd4CSA9a3L9InBBjNbgt0Bsae4ohRHCb6cpZJrYdd2mdFPh5GwfakRMoXCFJltFTnD2XgXb7CuMmCCOILuJ01JryQVqOmOdh7gs2cwY2Ly2nssNnxSexoTZS5dvO4cwEHiGFbB4GgU2ayg+PA8qTIZjiHtD+aPyZvx9OR08Cw9Xt6aEv9FjMJvw+1WTZHo7oAXfXsCZZcqZMLTvnXF33rsyuTcUeyxHSfFC3wHTzOu/db/OSjgaWtie88iqCibcqP47DtRCAKkjUepVatZQglOotQ5iNpo89u0HpwyPISNqEsozIfwseQ2LUGatreVqBuKrFupGKNcMu1ldfLIG0KQnzQHgVu2fWUcJEEPRW8PmXNyPH8RbqXQIZdE9462+/DIRF8qrrA/8qZhN9K+Ew02jn2iNCF2wztNPzN7FQzGqSbLAGdIVy9H/OqbC4xrUW0uYQ1hqA1dWwxkVVD097M1YELsCb7ljdtmjuMp1ch7reOHnRlPBxy1Xmv2cy0VJ31Z85sb9EKww2gYPYYF5Bp9xUovug=
